%ifndef __IONUM_INC__
%define __IONUM_INC__

; 32 bites beolvasas
extern ReadInt

; 32 bites kiiratas
extern WriteInt

; 64 bites beolvasas
extern ReadInt64

; 64 bites kiiratas
extern WriteInt64

; 32 bites beolvasas
extern ReadBin

; 32 bites kiiratas
extern WriteBin

; 64 bites beolvasas
extern ReadBin64

; 64 bites kiiratas
extern WriteBin64

; 32 bites beolvasas
extern ReadHex

; 32 bites kiiratas
extern WriteHex

; 64 bites beolvasas
extern ReadHex64

; 64 bites kiiratas
extern WriteHex64

%endif